// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WxsNye5Z9aODrtXlROjdleZiPydLanM',
    appId: '1:183719920937:web:f970209cd0f45876e02338',
    messagingSenderId: '183719920937',
    projectId: 'todo-app-751ac',
    authDomain: 'todo-app-751ac.firebaseapp.com',
    storageBucket: 'todo-app-751ac.appspot.com',
    measurementId: 'G-HX6FY2GLX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsg_KLNNVDmyQx_vhqSk5_MZGZLzyr6q0',
    appId: '1:183719920937:android:48d949af3dd6f8ace02338',
    messagingSenderId: '183719920937',
    projectId: 'todo-app-751ac',
    storageBucket: 'todo-app-751ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINP14KFdRdOMTe36n-igrlpq9KTYcz7w',
    appId: '1:183719920937:ios:c6ee84338f56ac2be02338',
    messagingSenderId: '183719920937',
    projectId: 'todo-app-751ac',
    storageBucket: 'todo-app-751ac.appspot.com',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINP14KFdRdOMTe36n-igrlpq9KTYcz7w',
    appId: '1:183719920937:ios:9bcd019e443ac30be02338',
    messagingSenderId: '183719920937',
    projectId: 'todo-app-751ac',
    storageBucket: 'todo-app-751ac.appspot.com',
    iosBundleId: 'com.example.todoAppFlutter.RunnerTests',
  );
}
